---

- name: run commands on Cisco IOS XE devices
  hosts: ios_xe
  gather_facts: no

  tasks:
    - name: Show ip route output
      cisco.ios.ios_command:
        commands: show wireless tag site summary | i "{{ sitetag_name }}"
      register: sitetag_output

    - name: configure sitetag
      cisco.ios.ios_config:
        lines: wireless tag site "{{ sitetag_name }}"
      when: sitetag_output is search("{{ sitetag_name }}")


