---

- name: run commands on Cisco IOS XE devices
  hosts: ios_xe
  gather_facts: no

  tasks:
    - name: Show wireless tag site summary
      cisco.ios.ios_command:
        commands: show wireless tag site summary | i "{{ sitetag_name }}"
      register: sitetag_output

    - name: configure sitetag
      cisco.ios.ios_config:
        lines: wireless tag site "{{ sitetag_name }}"
      register: config_output
      
    - name: print config_output
      debug:
        var: config_output
