---

- name: run commands on Cisco IOS XE devices
  hosts: ios_xe
  gather_facts: no

  tasks:
    - name: configure sitetag
      cisco.ios.ios_config:
        lines: wireless tag site "{{ sitetag_name }}"
      args:
        warn: false # THIS is the feature request -- the ability to disable the idempotency warning flag in a single task
      register: config_output
      
    - name: print config_output
      debug:
        var: config_output
