---

- name: run commands on Cisco IOS XE devices
  hosts: ios_xe
  gather_facts: no

  tasks:
    - name: add site tag to all WLCs
      ios_command:
        commands:
            - wireless tag site "{{ sitetag_name }}"
