- name : sitetag
  hosts: C9800
  connection: netconf
  gather_facts: no

  tasks:
    - name: sitetag
        netconf_config:
          xml: |
            <config xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
              <site-cfg-data xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-wireless-site-cfg">
                <site-tag-configs>
                  <site-tag-config>
                    <site-tag-name>Example</site-tag-name>
                    <description>Hi-there</description>
                    <image-download-profile-name/>
                    <dhcp-bcast/>
                  </site-tag-config>
                </site-tag-configs>
              </site-cfg-data>
            </config>
