- name: Configure using Local CSV
  hosts: C9800
  vars:
    csv_file_path: "APs2Config.csv"  # Update this path to your local CSV file

  vars_prompt:
    - name: use_csv_input
      prompt: "Do you want to use a local CSV file as input? (yes/no)"
      private: no

  tasks:
    - ios_command:
        commands:
          - show version | i uptime
      register: show

    - debug:
        var: show.stdout_lines

    - name: Load CSV content
      when: use_csv_input == "yes"
      command: python3 csv_parser.py "{{ csv_file_path }}"
      register: csv_content

    - name: Define List from CSV
      when: use_csv_input == "yes"
      debug:
        var: csv_content.stdout_lines

    - name: Debug CSV Content Element
      debug:
        var: csv_content.stdout_lines[0]


    - name: Apply names based on Do from CSV
      when: use_csv_input == "yes"
      ignore_errors: true
      loop: "{{ csv_content.stdout_lines[0] }}"
      loop_control:
        loop_var: item_csv
      tasks:
        - name: Apply name if 'do' is 'yes'
          when: item_csv.do == "yes"
          ios_command:
            commands:
              - "ap name {{ item_csv.DefaultName }} name {{ item_csv.Name }}"







