- name: Configure using Local CSV
  hosts: C9800
  vars:
    csv_file_path: "APs2Config.csv"  # Update this path to your local CSV file

  vars_prompt:
    - name: use_csv_input
      prompt: "Do you want to use a local CSV file as input? (yes/no)"
      private: no

  vars:
    apmacs: []
    maclist: []

  tasks:
    - ios_command:
        commands:
          - show version | i uptime
      register: show

    - debug:
        var: show.stdout_lines

    - name: Load CSV content
      when: use_csv_input == "yes"
      set_fact:
        csv_content: "{{ lookup('file', csv_file_path) | from_csv }}"

    - name: Define List from CSV
      when: use_csv_input == "yes"
      debug:
        msg: "{{ csv_content }}"

    - name: Apply names based on Mac from CSV
      when: use_csv_input == "yes"
      ignore_errors: true
      ios_command:
        commands:
          - "ap name {{ item.defaultname }} name {{ item.name }}"
      loop: "{{ csv_content }}"
      when:
        - item.skip == "0"
