- name: Configure using Local CSV
  hosts: C9800
  vars:
    csv_file_path: "APs2Config.csv"  # Update this path to your local CSV file

  vars_prompt:
    - name: use_csv_input
      prompt: "Do you want to use a local CSV file as input? (yes/no)"
      private: no

  tasks:
    - ios_command:
        commands:
          - show version | i uptime
      register: show

    - debug:
        var: show.stdout_lines

    - name: Load CSV content
      when: use_csv_input == "yes"
      command: python3 csv_parser.py "{{ csv_file_path }}"
      register: csv_content

    - name: Define List from CSV
      when: use_csv_input == "yes"
      debug:
        var: csv_content.stdout_lines

    - name: Apply names based on Mac from CSV
      when: use_csv_input == "yes"
      ignore_errors: true
      ios_command:
        commands:
          - "ap name {{ item.defaultname }} name {{ item.name }}"
      loop: "{{ csv_content.stdout_lines }}"
      when:
        - item.skip == "0"
